version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-graph
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/test1234"
    volumes:
      - neo4j_data:/data
      - ./data_set/refined_dataset.csv:/import/refined_dataset.csv:ro  

volumes:
  neo4j_data:
